version: "3.8"

services:
  rabbit:
    image: "rabbitmq:3-management"
    hostname: my-rabbit
    ports:
      - "15672:15672"
      - "5672:5672"
  mongo:
    image: "mongo:5.0.8-focal"
    hostname: my-mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root